#sqlalchemy acts a bridge between python and mysql
#pymysql - python communicates with mysql server here
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine #creates the connection

engine = create_engine("mysql+pymysql://root:password@localhost:3306/ecommerce_analysis")

tables = {
     "customers": "olist_customers_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "payments": "olist_order_payments_dataset.csv",
    "products": "olist_products_dataset.csv",
    "reviews": "olist_order_reviews_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "geolocation": "olist_geolocation_dataset.csv",
    "category_translation": "product_category_name_translation.csv"
}
for table_name , file_name in tables.items():
    df = pd.read_csv(file_name)

    df.to_sql(
        name = table_name,
        con= engine,
        if_exists='replace',
        index=False
    )

print(f"{table_name} imported successfully")
print("\n all tables imported successfully")


#customers 
query = """
select count(*) from customers
"""
df = pd.read_sql(query,engine)
print(df)

#which state has highest number of customers
query = """
select customer_state, count(*) as total_customers
from customers
group by customer_state
order by total_customers desc;
"""

df = pd.read_sql(query,engine)
print(df)


plt.figure(figsize = (10,6))
plt.bar(df['customer_state'], df['total_customers'])
plt.title('Customers by state')
plt.xlabel('State')
plt.ylabel('Number of customers')

plt.show()

# Business Insight:
# SP has the highest number of customers,
# indicating the company's strongest customer base is in this state.

#revenue analysis
query = """
select customer_state , sum(payment_value) as total_revenue
from customers
inner join orders
on customers.customer_id = orders.customer_id 
inner join payments
on orders.order_id = payments.order_id
group by customer_state
order by total_revenue desc;
"""

df = pd.read_sql(query,engine)
print(df)

plt.figure(figsize= (10,6))
plt.bar(df['customer_state'] , df['total_revenue'])

plt.title("Revenue generated by state")
plt.xlabel("Customer state")
plt.ylabel('Total Revenue')
plt.xticks(rotation = 45)
plt.tight_layout()

plt.show()
# =====================================
# Business Insight
# =====================================
# 1. SP generates the highest revenue among all states.
# 2. Revenue is unevenly distributed across states.
# 3. The company may focus on growing lower-performing states.


#payment analysis
query = """
select payment_type , count(payment_type) as total_payments 
from payments
group by payment_type
order by count(payment_type) desc;
"""
df = pd.read_sql(query,engine)
print(df)

plt.figure(figsize= (10,6))
plt.bar(df['payment_type'] , df['total_payments'], color = 'crimson')
plt.title("Most preffered payment methods")
plt.xlabel('Payment type')
plt.ylabel('Number of payments')
plt.tight_layout()
plt.show()
# =====================================
# Business Insight
# =====================================
# 1. Credit cards are the most preferred payment method.
# 2. Other payment methods are used much less frequently.
# 3. The company should continue supporting the most popular payment methods.

#monthly revenue trend
query = """
select date_format(order_purchase_timestamp , '%%Y-%%m') as month,
sum(payment_value) as total_revenue
from orders
inner join payments
on orders.order_id = payments.order_id
group by month
order by month;
"""

df = pd.read_sql(query , engine)
print(df.head())

plt.figure(figsize = (12,6))
plt.plot(df['month'], df['total_revenue'], marker = 'o', color = 'royalblue')
plt.title('Monthly revenue trend')
plt.xlabel('Monthly')
plt.ylabel('Total revenue')
plt.xticks(rotation = 45)
plt.tight_layout()
plt.show()

# =====================================
# Business Insights
# =====================================
# 1. Revenue trends help identify periods of business growth and decline.
# 2. Peaks in revenue may indicate seasonal demand or successful promotional campaigns.
# 3. Understanding monthly trends helps the business plan inventory, staffing, and marketing activities.

#revenue by product category
query = """
select product_category_name , sum(price) as total_revenue
from order_items
inner join products on
order_items.product_id = products.product_id
group by product_category_name
order by total_revenue desc
limit 10;
"""
df = pd.read_sql(query , engine)
print(df.head())

plt.figure(figsize=(12,7))

plt.barh(df['product_category_name'] , df['total_revenue']
         ,color = 'orange')

plt.title('Top 10 categories by revenue')
plt.xlabel('Revenue')
plt.ylabel('Product category')

plt.gca().invert_yaxis() #get current axis and flip the vertical axis
plt.tight_layout()
plt.show()

# =====================================
# Business Insights
# =====================================
# 1. A few product categories contribute a significant portion of total revenue.
# 2. High-performing categories should remain a priority for inventory and promotions.
# 3. Low-performing categories can be reviewed for pricing, marketing, or product improvements.

#Top 10 citites by revenue
query = """
select customer_city ,
sum(payment_value) as total_revenue
from customers
inner join orders
on customers.customer_id = orders.customer_id
inner join payments
on orders.order_id = payments.order_id
group by customer_city
order by total_revenue desc
limit 10;
"""
df = pd.read_sql(query , engine)
print(df.head())

plt.figure(figsize=(12,6))
plt.barh(df['customer_city'], df['total_revenue'], color = 'green')
plt.title('Top 10 cities by revenue')
plt.xlabel('Revenue')
plt.ylabel('City')

plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

# =====================================
# Business Insights
# =====================================
# 1. A small number of cities generate a large share of the company's revenue.
# 2. These cities represent key markets where customer demand is highest.
# 3. Expanding successful business strategies to similar cities could increase overall revenue.

#Payment installments
query = """
select payment_installments , count(*) as total_payments
from payments
group by payment_installments
order by total_payments desc;
"""
df = pd.read_sql(query , engine)
print(df.head())

plt.figure(figsize=(12,7))
plt.bar(df['payment_installments'], df['total_payments'], color = 'royalblue')
plt.title('Payments Installment distribution')
plt.xlabel('Installments')
plt.ylabel('Number of payments')

plt.tight_layout()
plt.show()

# =====================================
# Business Insights
# =====================================
# 1. Most customers prefer a limited number of installment options.
# 2. Flexible installment plans may encourage higher-value purchases.
# 3. Understanding installment preferences helps optimize payment strategies and financing options.

#revenue by payment type
query = """
select payment_type , sum(payment_value) as total_revenue
from payments
group by payment_type
order by total_revenue desc;
"""
df = pd.read_sql(query , engine)
print(df.head())

plt.figure(figsize=(12,7))
plt.bar(df['payment_type'] , df['total_revenue'], color = 'pink')
plt.title('Payment Type Distribution')
plt.xlabel('Payment types')
plt.ylabel('Total revenue')

plt.tight_layout()
plt.show()

# =====================================
# Business Insights
# =====================================
# 1. Different payment methods contribute differently to total revenue.
# 2. The highest-revenue payment method indicates customer purchasing preferences.
# 3. Supporting secure and convenient payment options can help maintain or improve sales.
